

import React from "react";
import Navbar from "../components/Navbar";
import NewDrink from "../components/new-drink";
import Toppings from "../components/Toppings";
import Home from "./Home";
import Menu from "./Menu";
import NotFound from "./NotFound";
import {BrowserRouter as Router,Switch, Route } from "react-router-dom/cjs/react-router-dom.min";
import Login from "./Login";
import { AuthProvider } from "../hooks/useAuth";
import ProtectedRoute from '../components/Protected-route';
const Admin = () => {
  return (
    <>
    <AuthProvider>
    <Router>
    <Switch>
      <Route path="/admin" component={NewDrink}/>
      <Route path="/toppings" component={Toppings}/>
      <Route path="/menu" component={Menu}/>
      <Route path="/login" component={Login}/>
      <ProtectedRoute path="/admin" component={NewDrink } level={2}/>
      <Route exact path="/" component={Home}/>
      <Route component={NotFound}/>
    </Switch>
    </Router>
    </AuthProvider>
    </>
  )
}

export default Admin;


// Generated by CodiumAI

describe('Admin', () => {

    // Submitting the form with a large image file
    it('should not submit the form with a large image file', () => {
      const wrapper = mount(<Admin />);
      const form = wrapper.find('form');
      const fileInput = wrapper.find('input[type="file"]');
      const file = new File([''], 'image.jpg', { type: 'image/jpeg', size: 1024 * 1024 * 10 });
      Object.defineProperty(fileInputRef.current, 'files', { value: [file] });
      fileInput.simulate('change', { target: { files: [file] } });
      form.simulate('submit', { preventDefault: jest.fn() });
      expect(addDrink).not.toHaveBeenCalled();
    });
});
